name: Build

on:
  push:
    tags:
        - "v*"
  workflow_dispatch:
  
  
env:
  FACE_SDK_TAG: v3.27.0    


jobs:
    windows-build:
      runs-on: windows-latest
      strategy:
        matrix:
            python-versions: [[38, 3.8], [39, 3.9], [310, 3.10], [311, 3.11], [312, 3.12], [313, 3.13]]

      steps:
        - uses: actions/checkout@v4

        - name: Clone FaceSDK
          uses: actions/checkout@v4
          with:
            repository: 3DiVi/face-sdk
            path: FaceSDK
            ref: ${{ env.FACE_SDK_TAG }}

        - name: Remove other files from FaceSDK
          shell: bash
          working-directory: FaceSDK
          run: |
              mv include ../includeFaceSDK
              rm -rf *
              mv ../includeFaceSDK ./include

        - name: Install Python
          run: |
              choco install python${{ matrix.python-versions[0] }} -y
              Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
              refreshenv
              python --version

        - name: Install build
          run: python${{ matrix.python-versions[1] }} -m pip install build

        - name: Build
          shell: cmd
          run: python${{ matrix.python-versions[1] }} -m build

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.python-versions }}-windows
            path: dist\*.whl


    linux-build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Clone FaceSDK
          uses: actions/checkout@v4
          with:
            repository: 3DiVi/face-sdk
            path: FaceSDK
            ref: ${{ env.FACE_SDK_TAG }}

        - name: Remove other files from FaceSDK
          shell: bash
          working-directory: FaceSDK
          run: |
              mv include ../includeFaceSDK
              rm -rf *
              mv ../includeFaceSDK ./include

        - name: Install build
          run: pip install build

        - name: Build
          run: python3 -m build

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: linux
            path: dist/*.tar.gz
